version: 2.1
jobs:
  sdkman:
    working_directory: ~/kotlin-playground
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run: sudo apt update && sudo apt install curl
      - run:
          name: Installing SDKMAN!
          command: |
            curl -s "https://get.sdkman.io" | bash
            echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
            echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            echo 'export SDKMAN_DIR="$HOME/.sdkman"' >> $BASH_ENV
            echo 'source "$HOME/.sdkman/bin/sdkman-init.sh"' >> $BASH_ENV
      - run: sdk version
      - run: sdk install kotlin
      - run: java -version
      - run: javac -version
      - run: kotlinc -version
      - run: kotlinc-jvm HelloWorld.kt
      - run: kotlinc HelloWorld.kt -include-runtime -d helloworld.jar
      - run: kotlin helloworld.jar
      - run: java -jar helloworld.jar
      - run: java -classpath .:$HOME/.sdkman/candidates/kotlin/1.7.21/lib/kotlin-runner.jar HelloWorldKt
workflows:
  version: 2
  build:
    jobs:
      - sdkman
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: /master/
    jobs:
      - sdkman
